### PR TITLE
update custom properties within the entity editor

### PR DESCRIPTION
**Pull request by jum-s**
solving #346

### CODE REVIEW

**Comment by maxlath** [comment]
There are conflicts with master, could you rebase the branch?

**Comment by jum-s** [comment]
done

**Comment by maxlath** [comment]
Instead of that odd "show more properties" button, what about having an entry in the `entity_edit_menu` like "customize editable properties"?

**Comment by jum-s** [comment]
done in 93127258f

**Comment by maxlath** [comment]
I'm having second thoughts on this:
* I wasn't fond of the button at the bottom, having it in the menu makes it actually harder to reach :/
* I wonder if reusing the list of properties displayed on entities layouts to customize the editor and vice versa will not an annoying behavior: for instance, let's say that I found the ID for a work in the Czech national library (P3184); I don't have it in my custom properties list, so I would have to customize my properties once to display it, set the ID, and customize again as I'm not that interested in that property. What about first showing only the properties in the custom properties list, and then have a `WrapToggler` like in the `entity_create` to display all the available properties in that section, but without changing the custom properties list?

**Comment by jum-s** [comment]
I agree it should be more accessible. 

To consider: the initial proposition included a modal, the intent was to signify that one can easily customize props. By leaving only a view in settings, someone may never know that the feature exists.

Question in your scenario, what if no custom props are checked in a category ? (Now, no category title is displayed, nothing hints that more props are available despite the fact that the user have scrolled all the way down there.)

So what about displaying all categories no matter what: 
- folded category if no custom prop exists
- unfolded if some custom props

If unfolded,  always display the wrapper you mention

What about then having a information box at the bottom of the wrapper, that would invite to customize the properties with a links to the settings?

**Comment by jum-s** [comment]
This PR was a nice feature testing discussion, now depreciated in favor of a clean rewrite in #406.

**Pull request closed without merging**
